from ProgramMenu import Main
import os.path
import csv

Start = Main()
# /////////////////
# CREATE TABLE INVESTOR
# ( INVESTOR_ID int NOT NULL,
  # INVESTOR_NAME char(50) NOT NULL,
  # INVESTOR_EMAIL varchar(50) NOT NULL,
  # PRIMARY KEY (INVESTOR_ID),
  # CHECK(INVESTOR_ID >= 1)
# );

# CREATE TABLE CRYPTOCURRENCY
# ( CRYPTOCURRENCY_ID int NOT NULL,
  # CRYPTOCURRENCY_NAME char(50) NOT NULL,
  # CRYPTOCURRENCY_UNIT_PRICE float NOT NULL,
  # PRIMARY KEY (CRYPTOCURRENCY_ID),
  # CHECK(CRYPTOCURRENCY_ID >= 1)
# );

# CREATE TABLE INVESTMENT
# ( INVESTMENT_INVESTOR_ID int NOT NULL,
  # INVESTMENT_CRYPTOCURRENCY_ID int NOT NULL,
  # INVESTMENT_NUMSHARES int NOT NULL,
  # INVESTMENT_PURCHASEPRICE float NOT NULL,
  # INVESTMENT_STILLOWNED int NOT NULL,
  # PRIMARY KEY (INVESTMENT_INVESTOR_ID, INVESTMENT_CRYPTOCURRENCY_ID),
  # FOREIGN KEY (INVESTMENT_INVESTOR_ID) REFERENCES INVESTOR(INVESTOR_ID),
  # FOREIGN KEY (INVESTMENT_CRYPTOCURRENCY_ID) REFERENCES CRYPTOCURRENCY(CRYPTOCURRENCY_ID),
  # CHECK (INVESTMENT_NUMSHARES >= 1),
  # CHECK (INVESTMENT_PURCHASEPRICE >= 0.00),
  # CHECK (INVESTMENT_STILLOWNED >= 1)
# );